---
- name: Install and configure Java
  hosts: artifactory-server
  sudo: yes
  tasks:
    - action: ping
    - name: download nexus 
      shell: wget https://download.sonatype.com/nexus/oss/nexus-latest-bundle.tar.gz
    - name: extract nexus nexus-latest-bundle.tar.gz file 
      shell: tar -xvzf nexus-latest-bundle.tar.gz
    - name: download sonarqube community version 
      shell: wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.3.zip
    - name: install unzip
      apt: name=unzip update_cache=yes state=latest
    - name: unzip sonarqube 
      shell: unzip sonarqube-7.3.zip
    - name: setup sonatype-work permissions 
      shell: chown -R ubuntu:ubuntu sonatype-work
    - name: setup sonarqube permissions 
      shell: chown R ubuntu:ubuntu sonarqube*
    - name: setup nexus permissions 
      shell: chown R ubuntu:ubuntu nexus*